### ISSUE TITLE
2010 Beneficiary Summary Sample 1 Left Out

### ISSUE THREAD

**Issue by jinyoung5484** [audiracmichelle/cms_duckdb#9]
Hey Michelle,

I noticed Sample 1 for the 2010 beneficiary summary was intentionally left out due to an error in source data.

I just wanted to confirm that the number of records for 2010 should be 2,142,344 instead of 2,255,098 as shown in the instruction document.

Should I still leave out 2010 Sample 1 or not?

Thank you,
Jinyoung

**Comment by audiracmichelle** [comment]
Hi! Feel free to add a special case to the code to read sample 1 of year 2010, it can be a hardcoded case. I believe the error is only a naming error, otherwise you can leave out and explain discrepancy details in the README :) .

Thanks for reporting the mismatch! The number of 2010 records reported by official CMS is 2,255,098; interestingly it has an error. I validated the number you report here as well https://github.com/audiracmichelle/cms_duckdb/blob/main/notebooks/eda_cms.ipynb Out [19]

**Comment by jinyoung5484** [comment]
Thank you! 
I will go back and see if I can still use sample 1.
I see that you have been using duckdb for most analyses.
I've been using pandas, seaborn, and matplotlib for simple analyses and visualizations for the given analyses, but do you recommend using duckdb?
Just in case, if you want to see how I have done so far, here is a notebook that I have done for beneficiary data

**Comment by audiracmichelle** [comment]
This repo is a dump of code that I used to support a demo, but is really not properly organized. For your repository, focus on the data storytelling and the organization so that the content is easy to follow. Pandas, seaborn, and matplotlib are good for that purpose, so no need to use duckdb.
I will restrain from opening your work until you have finished all deliverables for fair comparison with other candidates :)
But please keep you work in a private repo (sorry this omission, it should have been indicated in the instructions document!)

**Comment by jinyoung5484** [comment]
My apology for privacy. I will change it to a private repo. 
Thank you for your response!
